local COMMON = require "libs.common"
local GUI = require "assets.templates.gui_templates"
local SM = require "libs_project.sm"
local LEVELS = require "scenes.game.levels.levels"

local Script = COMMON.new_n28s()

function Script:bind_vh()
	self.view = {
		btn_back = GUI.Button("btn_back"),
		btn_test_lvl_1 = GUI.Button("btn_test_lvl_1"),
		btn_test_lvl_2 = GUI.Button("btn_test_lvl_2")
	}
end

function Script:init_gui()
	self.view.btn_back:set_input_listener(function ()
		SM:back()
	end)
	self.view.btn_test_lvl_1:set_input_listener(function ()
		SM:show(SM.SCENES.GAME_SCENE, {level_id = LEVELS.TESTS.TEST_BIG_EMPTY})
	end)

	self.view.btn_test_lvl_2:set_input_listener(function ()
		SM:show(SM.SCENES.GAME_SCENE, {level_id = LEVELS.TESTS.TEST})
	end)
end

function Script:init()
	self:bind_vh()
	self:init_gui()
	COMMON.input_acquire()
end

function Script:update(dt)end

function Script:final()
	COMMON.input_release()
end


function Script:on_input(action_id, action)
	if(self.view.btn_back:on_input(action_id,action).consumed) then return true end
	if(self.view.btn_test_lvl_1:on_input(action_id,action).consumed) then return true end
	if(self.view.btn_test_lvl_2:on_input(action_id,action).consumed) then return true end
end



COMMON.N28S.register(Script())